[mypy]
python_version = 3.12
strict = true
warn_return_any = true
warn_unused_ignores = true
disallow_untyped_defs = true
files = src/lina_redshift

[mypy-faker.*]
ignore_missing_imports = true

[mypy-pytest_postgresql.*]
ignore_missing_imports = true

[mypy-psycopg2.*]
ignore_missing_imports = true
