[mypy]
python_version = 3.12
strict = true
warn_return_any = true
warn_unused_ignores = true
disallow_untyped_defs = true
files = src/lina_core, src/lina_redshift, src/lina_users, src/lina_vendors

[mypy-opensearchpy.*]
ignore_missing_imports = true

[mypy-requests_aws4auth.*]
ignore_missing_imports = true

[mypy-testcontainers.*]
ignore_missing_imports = true

[mypy-faker.*]
ignore_missing_imports = true

[mypy-pytest_postgresql.*]
ignore_missing_imports = true

[mypy-psycopg2.*]
ignore_missing_imports = true
