"""Translate Redshift-flavored DDL to Postgres-compatible DDL.

Production target is Redshift. The shim runs only when the migration runner
targets Postgres (unit tests, local dev). Each translation has a unit test.
"""

from __future__ import annotations

import re


class UnsupportedDialectError(RuntimeError):
    """Raised when input SQL contains Redshift-only constructs we do not handle."""


_ENCODINGS = (
    "AZ64",
    "LZO",
    "ZSTD",
    "RAW",
    "BYTEDICT",
    "DELTA",
    "MOSTLY8",
    "MOSTLY16",
    "MOSTLY32",
    "RUNLENGTH",
    "TEXT255",
    "TEXT32K",
)
_ENCODE_RE = re.compile(
    r"\s+ENCODE\s+(?:" + "|".join(_ENCODINGS) + r")",
    flags=re.IGNORECASE,
)

_DISTSTYLE_RE = re.compile(
    r"\s+DISTSTYLE\s+(?:AUTO|EVEN|ALL|KEY\s*\([^)]*\))",
    flags=re.IGNORECASE,
)
_DISTKEY_RE = re.compile(r"\s+DISTKEY\s*\([^)]*\)", flags=re.IGNORECASE)

_SORTKEY_RE = re.compile(
    r"\s+(?:COMPOUND\s+|INTERLEAVED\s+)?SORTKEY"
    r"(?:\s+AUTO|\s*\([^)]*\))",
    flags=re.IGNORECASE,
)

_BACKUP_RE = re.compile(r"\s+BACKUP\s+(?:YES|NO)", flags=re.IGNORECASE)

_IDENTITY_RE = re.compile(
    r"\bIDENTITY\s*\(\s*\d+\s*,\s*\d+\s*\)",
    flags=re.IGNORECASE,
)

_AUTO_REFRESH_RE = re.compile(r"\s+AUTO\s+REFRESH\s+(?:YES|NO)", flags=re.IGNORECASE)

_VARCHAR_MAX_RE = re.compile(r"varchar\s*\(\s*max\s*\)", flags=re.IGNORECASE)

# Redshift-only tokens we have not implemented translations for.
_UNSUPPORTED_TOKENS = (
    re.compile(r"\bSUPER\b", flags=re.IGNORECASE),
    re.compile(r"\bHLLSKETCH\b", flags=re.IGNORECASE),
    re.compile(r"\bGEOMETRY\b", flags=re.IGNORECASE),
)


def translate_for_postgres(sql: str) -> str:
    """Apply all Redshift→Postgres translations. Raise on unsupported constructs."""
    for token_re in _UNSUPPORTED_TOKENS:
        if token_re.search(sql):
            raise UnsupportedDialectError(
                f"SQL contains Redshift-only construct not handled by the shim: {sql!r}"
            )
    out = sql
    out = _ENCODE_RE.sub("", out)
    out = _DISTSTYLE_RE.sub("", out)
    out = _DISTKEY_RE.sub("", out)
    out = _SORTKEY_RE.sub("", out)
    out = _BACKUP_RE.sub("", out)
    out = _AUTO_REFRESH_RE.sub("", out)
    out = _IDENTITY_RE.sub("GENERATED BY DEFAULT AS IDENTITY", out)
    return _VARCHAR_MAX_RE.sub("varchar", out)
