"""Unit tests for the Redshift→Postgres dialect shim."""

from __future__ import annotations

import pytest

from lina_redshift.dialect import (
    UnsupportedDialectError,
    translate_for_postgres,
)


@pytest.mark.unit
def test_strips_diststyle_auto() -> None:
    sql = "CREATE TABLE t (id varchar) DISTSTYLE AUTO;"
    assert "DISTSTYLE" not in translate_for_postgres(sql)


@pytest.mark.unit
def test_strips_diststyle_key() -> None:
    sql = "CREATE TABLE t (id varchar) DISTKEY(id) DISTSTYLE KEY(id);"
    out = translate_for_postgres(sql)
    assert "DISTSTYLE" not in out
    assert "DISTKEY" not in out


@pytest.mark.unit
def test_strips_diststyle_even() -> None:
    assert "DISTSTYLE" not in translate_for_postgres("CREATE TABLE t (id int) DISTSTYLE EVEN;")


@pytest.mark.unit
def test_strips_diststyle_all() -> None:
    assert "DISTSTYLE" not in translate_for_postgres("CREATE TABLE t (id int) DISTSTYLE ALL;")


@pytest.mark.unit
def test_strips_sortkey_auto() -> None:
    assert "SORTKEY" not in translate_for_postgres("CREATE TABLE t (id int) SORTKEY AUTO;")


@pytest.mark.unit
def test_strips_sortkey_columns() -> None:
    sql = "CREATE TABLE t (id int, dt date) SORTKEY (dt, id);"
    assert "SORTKEY" not in translate_for_postgres(sql)


@pytest.mark.unit
def test_strips_compound_sortkey() -> None:
    sql = "CREATE TABLE t (id int, dt date) COMPOUND SORTKEY(dt);"
    assert "SORTKEY" not in translate_for_postgres(sql)


@pytest.mark.unit
def test_strips_interleaved_sortkey() -> None:
    sql = "CREATE TABLE t (id int, dt date) INTERLEAVED SORTKEY(dt, id);"
    assert "SORTKEY" not in translate_for_postgres(sql)


@pytest.mark.unit
@pytest.mark.parametrize(
    "encoding",
    [
        "AZ64",
        "LZO",
        "ZSTD",
        "RAW",
        "BYTEDICT",
        "DELTA",
        "MOSTLY8",
        "MOSTLY16",
        "MOSTLY32",
        "RUNLENGTH",
        "TEXT255",
        "TEXT32K",
    ],
)
def test_strips_column_encode(encoding: str) -> None:
    sql = f"CREATE TABLE t (id varchar ENCODE {encoding});"
    out = translate_for_postgres(sql)
    assert "ENCODE" not in out


@pytest.mark.unit
def test_strips_backup_no() -> None:
    sql = "CREATE TABLE t (id int) BACKUP NO;"
    assert "BACKUP" not in translate_for_postgres(sql)


@pytest.mark.unit
def test_strips_backup_yes() -> None:
    sql = "CREATE TABLE t (id int) BACKUP YES;"
    assert "BACKUP" not in translate_for_postgres(sql)


@pytest.mark.unit
def test_replaces_identity_with_generated() -> None:
    sql = "CREATE TABLE t (id int IDENTITY(1, 1));"
    out = translate_for_postgres(sql)
    assert "IDENTITY(" not in out
    assert "GENERATED BY DEFAULT AS IDENTITY" in out


@pytest.mark.unit
def test_strips_auto_refresh_yes() -> None:
    sql = "CREATE MATERIALIZED VIEW mv AS SELECT 1 AUTO REFRESH YES;"
    out = translate_for_postgres(sql)
    assert "AUTO REFRESH" not in out


@pytest.mark.unit
def test_replaces_varchar_max() -> None:
    sql = "CREATE TABLE t (note varchar(max));"
    out = translate_for_postgres(sql)
    assert "varchar(max)" not in out
    assert "varchar" in out  # plain varchar with no length is unlimited in Postgres


@pytest.mark.unit
def test_idempotent_when_no_redshift_clauses() -> None:
    sql = "CREATE TABLE t (id varchar PRIMARY KEY);"
    assert translate_for_postgres(sql) == sql


@pytest.mark.unit
def test_unknown_redshift_only_token_raises() -> None:
    sql = "CREATE TABLE t (data SUPER);"
    with pytest.raises(UnsupportedDialectError):
        translate_for_postgres(sql)
